
export const tataTertibData = {
  kehadiran: {
    ringan: [
      { deskripsi: "Datang terlambat tanpa alasan.", poin: 5 },
      { deskripsi: "Tidur di kelas.", poin: 5 },
      { deskripsi: "Tidak membawa buku sesuai jadwal.", poin: 5 },
      { deskripsi: "Tidak membuat tugas sekolah.", poin: 5 },
      { deskripsi: "Tidak mengikuti jam tambahan remedial.", poin: 5 },
    ],
    sedang: [
      { deskripsi: "Pulang sebelum waktunya tanpa izin.", poin: 10 },
      { deskripsi: "Tidak mengikuti upacara bendera.", poin: 10 },
      { deskripsi: "Bolos pelajaran.", poin: 10 },
      { deskripsi: "Menitip absen palsu.", poin: 10 },
      { deskripsi: "Menggunakan alasan palsu untuk tidak masuk.", poin: 10 },
      { deskripsi: "Menghilang saat jam istirahat.", poin: 10 },
      { deskripsi: "Membuat keributan di kelas.", poin: 10 },
      { deskripsi: "Tidak mengikuti jadwal piket kelas.", poin: 10 },
      { deskripsi: "Membuat catatan kehadiran palsu.", poin: 10 },
      { deskripsi: "Mengabaikan panggilan guru.", poin: 10 },
    ],
    berat: [
      { deskripsi: "Tidak hadir tanpa keterangan (alpha) berulang.", poin: 20 },
      { deskripsi: "Tidak hadir saat kegiatan ekstrakurikuler wajib.", poin: 20 },
      { deskripsi: "Menolak hadir di kegiatan sekolah.", poin: 20 },
      { deskripsi: "Membolos saat praktek industri (PKL).", poin: 20 },
    ],
  },
  seragam: {
    ringan: [
      { deskripsi: "Tidak memakai seragam lengkap.", poin: 3 },
      { deskripsi: "Seragam kotor atau tidak rapi.", poin: 3 },
      { deskripsi: "Tidak memakai ikat pinggang sesuai ketentuan.", poin: 3 },
      { deskripsi: "Kaos kaki tidak sesuai aturan.", poin: 3 },
      { deskripsi: "Seragam tidak dimasukkan.", poin: 3 },
      { deskripsi: "Tidak memakai name tag.", poin: 3 },
    ],
    sedang: [
      { deskripsi: "Memakai atribut yang tidak sesuai.", poin: 10 },
      { deskripsi: "Memakai sepatu tidak sesuai aturan.", poin: 10 },
      { deskripsi: "Memakai jaket non-sekolah di kelas.", poin: 10 },
      { deskripsi: "Rambut gondrong (untuk siswa).", poin: 10 },
      { deskripsi: "Rambut dicat/bleaching.", poin: 10 },
      { deskripsi: "Memakai aksesoris berlebihan.", poin: 10 },
      { deskripsi: "Kuku panjang atau dicat.", poin: 10 },
      { deskripsi: "Memakai seragam olahraga di luar jam olahraga.", poin: 10 },
      { deskripsi: "Tidak memakai topi saat upacara (jika diwajibkan).", poin: 10 },
      { deskripsi: "Seragam tidak sesuai hari.", poin: 10 },
      { deskripsi: "Menggunakan make-up berlebihan.", poin: 10 },
    ],
    berat: [
      { deskripsi: "Celana dipendekkan atau dimodifikasi.", poin: 15 },
      { deskripsi: "Rok di atas lutut (untuk siswi).", poin: 15 },
      { deskripsi: "Memakai lensa kontak warna.", poin: 15 },
    ],
  },
  lingkungan: {
    ringan: [
      { deskripsi: "Membuang sampah sembarangan.", poin: 5 },
      { deskripsi: "Tidak menjaga kebersihan kelas.", poin: 5 },
      { deskripsi: "Mengotori kamar mandi.", poin: 5 },
      { deskripsi: "Mengotori papan tulis.", poin: 5 },
      { deskripsi: "Tidak mengikuti jadwal piket kelas/bengkel/lab.", poin: 5 },
    ],
    sedang: [
      { deskripsi: "Mencorat-coret meja, kursi, atau dinding.", poin: 15 },
      { deskripsi: "Membawa makanan/minuman ke dalam kelas.", poin: 15 },
      { deskripsi: "Menyimpan barang berbau busuk.", poin: 15 },
      { deskripsi: "Memindahkan peralatan kelas tanpa izin.", poin: 15 },
      { deskripsi: "Mematikan listrik/kipas/AC sembarangan.", poin: 15 },
      { deskripsi: "Tidak mengembalikan alat praktik ke tempatnya.", poin: 15 },
    ],
    berat: [
      { deskripsi: "Merusak fasilitas kelas.", poin: 30 },
      { deskripsi: "Merusak tanaman sekolah.", poin: 30 },
      { deskripsi: "Mengambil barang milik sekolah tanpa izin.", poin: 30 },
      { deskripsi: "Menggunakan peralatan bengkel tanpa izin.", poin: 30 },
      { deskripsi: "Membawa hewan peliharaan ke sekolah.", poin: 30 },
      { deskripsi: "Mengotori halaman sekolah dengan kendaraan.", poin: 30 },
    ],
  },
  etika: {
    ringan: [
      { deskripsi: "Berbicara kasar pada teman.", poin: 10 },
      { deskripsi: "Membuat keributan di perpustakaan.", poin: 10 },
      { deskripsi: "Memanggil guru dengan nama panggilan tidak sopan.", poin: 10 },
      { deskripsi: "Mengabaikan teguran guru.", poin: 10 },
      { deskripsi: "Memaki di grup kelas.", poin: 10 },
      { deskripsi: "Mencemooh prestasi teman.", poin: 10 },
    ],
    sedang: [
      { deskripsi: "Membentak guru/petugas sekolah.", poin: 20 },
      { deskripsi: "Menghina teman di depan umum.", poin: 20 },
      { deskripsi: "Memfitnah teman/guru.", poin: 20 },
      { deskripsi: "Memalak teman.", poin: 20 },
      { deskripsi: "Meniru tanda tangan guru/orangtua.", poin: 20 },
      { deskripsi: "Merokok di lingkungan sekolah.", poin: 20 },
      { deskripsi: "Membawa rokok atau korek api ke sekolah.", poin: 20 },
      { deskripsi: "Membuat hoaks terkait sekolah.", poin: 20 },
      { deskripsi: "Menghina fisik teman/guru.", poin: 20 },
      { deskripsi: "Membawa kendaraan tanpa SIM.", poin: 20 },
    ],
    berat: [
      { deskripsi: "Berbicara kasar pada guru.", poin: 40 },
      { deskripsi: "Bertengkar fisik di sekolah.", poin: 40 },
      { deskripsi: "Mengancam guru atau teman.", poin: 40 },
      { deskripsi: "Membawa senjata tajam tanpa izin.", poin: 40 },
      { deskripsi: "Mengintimidasi adik kelas (bullying).", poin: 40 },
      { deskripsi: "Berkelahi di luar sekolah membawa nama sekolah.", poin: 40 },
      { deskripsi: "Menghina agama/suku tertentu.", poin: 40 },
      { deskripsi: "Membawa minuman keras ke sekolah.", poin: 40 },
      { deskripsi: "Menggunakan narkoba.", poin: 40 },
    ],
  },
  akademik: {
    ringan: [
      { deskripsi: "Tidak mengumpulkan tugas.", poin: 5 },
      { deskripsi: "Tidak mengikuti ujian tanpa keterangan.", poin: 5 },
      { deskripsi: "Tidak memakai APD di bengkel/lab.", poin: 5 },
    ],
    sedang: [
      { deskripsi: "Menyontek saat ujian.", poin: 15 },
      { deskripsi: "Menggunakan HP saat ujian.", poin: 15 },
      { deskripsi: "Menjiplak tugas teman.", poin: 15 },
      { deskripsi: "Mengganggu jalannya ujian.", poin: 15 },
      { deskripsi: "Tidak membuat laporan praktik.", poin: 15 },
    ],
    berat: [
      { deskripsi: "Meminta atau membocorkan soal ujian.", poin: 20 },
      { deskripsi: "Menyuruh orang lain mengerjakan tugas.", poin: 20 },
      { deskripsi: "Memalsukan nilai atau tanda tangan.", poin: 20 },
      { deskripsi: "Memanipulasi data PKL.", poin: 20 },
      { deskripsi: "Menyalahgunakan alat bengkel/lab untuk pribadi.", poin: 20 },
    ],
  },
  teknologi: {
    ringan: [
      { deskripsi: "Menggunakan HP saat pelajaran tanpa izin.", poin: 5 },
      { deskripsi: "Bermain game di kelas.", poin: 5 },
      { deskripsi: "Menggunakan Wi-Fi sekolah untuk hal pribadi berlebihan.", poin: 5 },
    ],
    sedang: [
      { deskripsi: "Membuka situs terlarang di sekolah.", poin: 15 },
      { deskripsi: "Memotret guru tanpa izin.", poin: 15 },
      { deskripsi: "Membuat meme menghina guru.", poin: 15 },
      { deskripsi: "Menyebar gosip bohong online.", poin: 15 },
      { deskripsi: "Membajak akun media sosial teman.", poin: 15 },
    ],
    berat: [
      { deskripsi: "Menggunakan akun media sosial untuk menjelekkan sekolah.", poin: 20 },
      { deskripsi: "Membuat video bullying atau menyebar konten tidak pantas.", poin: 20 },
      { deskripsi: "Menyebar foto kelas tanpa izin.", poin: 20 },
      { deskripsi: "Mengirim pesan ancaman via grup.", poin: 20 },
      { deskripsi: "Membawa alat elektronik terlarang.", poin: 20 },
    ],
  },
  kegiatan: {
    ringan: [
      { deskripsi: "Tidak ikut kegiatan OSIS/Pramuka wajib.", poin: 10 },
      { deskripsi: "Mengabaikan aturan apel pagi.", poin: 10 },
      { deskripsi: "Tidak disiplin saat perkemahan/praktek luar.", poin: 10 },
    ],
    sedang: [
      { deskripsi: "Mengabaikan instruksi pembina upacara.", poin: 15 },
      { deskripsi: "Membuat gaduh saat acara resmi.", poin: 15 },
      { deskripsi: "Tidak hadir saat pembekalan PKL.", poin: 15 },
      { deskripsi: "Tidak mengembalikan perlengkapan kegiatan.", poin: 15 },
    ],
    berat: [
      { deskripsi: "Tidak ikut kegiatan PKL tanpa alasan.", poin: 30 },
      { deskripsi: "Membuat masalah saat study tour.", poin: 30 },
      { deskripsi: "Membuat kerusuhan saat pertandingan sekolah.", poin: 30 },
      { deskripsi: "Membawa senjata/bahan berbahaya saat kegiatan.", poin: 30 },
    ],
  },
  hukum: {
    berat: [
      { deskripsi: "Mengedarkan narkoba.", poin: 40 },
      { deskripsi: "Membawa senjata api.", poin: 40 },
      { deskripsi: "Menganiaya guru/teman.", poin: 40 },
      { deskripsi: "Mencuri barang di sekolah.", poin: 40 },
      { deskripsi: "Ikut tawuran antar sekolah.", poin: 40 },
      { deskripsi: "Merusak kendaraan guru/teman.", poin: 40 },
      { deskripsi: "Membakar fasilitas sekolah.", poin: 40 },
      { deskripsi: "Melakukan pelecehan seksual di sekolah.", poin: 40 },
      { deskripsi: "Melakukan perjudian di sekolah.", poin: 40 },
      { deskripsi: "Melakukan tindakan kriminal berat di luar sekolah membawa nama sekolah.", poin: 40 },
    ],
  },
};
